CREATE TABLE "GameDetails" (
	"System"	TEXT NOT NULL,
	"Title"	TEXT NOT NULL,
	"NameSimplified"	TEXT NOT NULL,
	"Compressed"	TEXT NOT NULL,
	"QtyPlayers"	NUMERIC NOT NULL DEFAULT 0,
	"Year"	INTEGER NOT NULL DEFAULT 0,
	"Status"	TEXT NOT NULL DEFAULT "",
	"ImageFileName"	TEXT NOT NULL DEFAULT "",
	"Region"	TEXT NOT NULL DEFAULT "",
	"Developer"	TEXT NOT NULL DEFAULT "",
	"ReleaseDate"	TEXT NOT NULL DEFAULT "",
	"Genre"	TEXT NOT NULL DEFAULT "",
	"NotesCore"	TEXT NOT NULL DEFAULT "",
	"NotesUser"	TEXT NOT NULL DEFAULT "",
	"FileFormat"	TEXT NOT NULL DEFAULT "",
	"Version"	TEXT NOT NULL DEFAULT "",
	"Description"	TEXT NOT NULL DEFAULT "",
	"Language"	TEXT NOT NULL DEFAULT "",
	"Rating"	TEXT NOT NULL DEFAULT "",
	"Publisher"	TEXT NOT NULL DEFAULT "",
	"WikipediaURL"	TEXT NOT NULL DEFAULT "",
	"StarRating"	REAL NOT NULL DEFAULT 0,
	"StarRatingVoteCount"	INTEGER NOT NULL DEFAULT 0,
	"FileName"	TEXT NOT NULL DEFAULT "",
	PRIMARY KEY("System","Title")
);
CREATE TABLE "Roms" (
	"Title"	TEXT NOT NULL,
	"NameSimplified"	TEXT NOT NULL,
	"NameOrg"	TEXT NOT NULL,
	"Compressed"	TEXT NOT NULL,
	"System"	INTEGER NOT NULL,
	"FilePath"	TEXT NOT NULL UNIQUE,
	"PreferredEmulator"	INTEGER NOT NULL DEFAULT 0,
	"ImagePath"	TEXT,
	"QtyPlayers"	INTEGER NOT NULL DEFAULT 1,
	"Status"	TEXT,
	"Region"	TEXT,
	"Developer"	TEXT,
	"ReleaseDate"	TEXT,
	"RomSize"	INTEGER,
	"Genre"	TEXT,
	"NotesCore"	TEXT,
	"NotesUser"	TEXT,
	"FileFormat"	TEXT,
	"Version"	TEXT,
	"Description"	TEXT,
	"Language"	TEXT,
	"Year"	INTEGER,
	"Rating"	TEXT,
	"Checksum"	TEXT,
	"CompressChecksum"	TEXT,
	"Publisher"	TEXT,
	"WikipediaURL"	TEXT,
	"StarRating"	REAL,
	"StarRatingVoteCount"	INTEGER,
	PRIMARY KEY("FilePath")
);

ALTER TABLE Roms ADD Favorite Boolean; 
ALTER TABLE Roms ADD Disable Boolean; 